### ISSUE TITLE
Suddenly not working...

### ISSUE THREAD

**Issue by iDavros** [bwssytems/restful-harmony#14]
Had everything set ap working well with ifttt but now, with out having changed any settings it won't connect to my hub... get this error

F:\Restful Harmony>java -jar -Dserver.port=8091 restful-harmony.jar 192.168.0.20
18:28:48.548 [main] INFO  c.b.restfulharmony.HarmonyRestServer - Harmony v1.0.0 rest server running....
18:28:48.668 [main] DEBUG n.w.harmony.HarmonyClient - listener[com.bwssystems.restfulharmony.HarmonyRestServer$1@2de8284b] added
Exception in thread "main" java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:179)
        at com.bwssystems.restfulharmony.HarmonyRestServer.execute(HarmonyRestServer.java:69)
        at com.bwssystems.restfulharmony.HarmonyRestServer.main(HarmonyRestServer.java:52)
Caused by: org.jivesoftware.smack.SmackException$ConnectionException
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:433)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:808)
        at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:396)
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:115)
        ... 2 more

The ip address hasn't changed and still can't get it to connect with a hub and router restart.

Can anyone help?

thanks!

**Comment by bwssytems** [comment]
Did anything change in your network? Such as IPs for the hub?

**Comment by iDavros** [comment]
Not that I can see... I had the harmony hub reserved to 192.168.0.1

Tried restful harmony in two computers but get the same error.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iDavros** [comment]
I meant 192.168.0.20

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iDavros** [comment]
This might be why...

https://www.home-assistant.io/blog/2018/12/17/logitech-harmony-removes-local-api/

**Comment by bwssytems** [comment]
Well that will suck! I'll take a look at my hub as well.

**Comment by ElYoM** [comment]
Hello,
Same problem for me with firmware v4.15.206 of harmony hub...
Do you think a workaround can be found?

**Comment by bwssytems** [comment]
Logitech has fixed this a while back.
