### ISSUE TITLE
unable to start the server with java error

### ISSUE THREAD

**Issue by jluc2808** [bwssytems/restful-harmony#16]
hello, when i start : 
java -jar restful-harmony-1.0.0.jar 192.168.1.32
i receive an error : 
   Exception in thread "main" java.lang.UnsupportedClassVersionError: com/bwssystems/restfulharmony/HarmonyRestServer : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

my java -version is : 
java -version
java version "1.7.0_221"
OpenJDK Runtime Environment (IcedTea 2.6.18) (linux-gnu build 1.7.0_221-b02)
OpenJDK 64-Bit Server VM (build 24.221-b02, mixed mode)

is there an obvious problem with this java version ? 

thanks

**Comment by bwssytems** [comment]
I will take a look at that jar. It may be compiled with java 11
