### ISSUE TITLE
Can't get 0.1.5. to run...

### ISSUE THREAD

**Issue by quenthal** [bwssytems/restful-harmony#3]
0.1.4. starts and runs just fine.

pi@raspberrypi:~ $ sudo java -jar restful-harmony-0.1.5.jar 192.168.1.105 xxxx@gmail.com pass123123
[main] INFO com.bwssystems.restfulharmony.HarmonyRestServer - Harmony v0.1.5 rest server running....
maaliskuuta 30, 2016 2:03:19 IP. org.jivesoftware.smack.provider.ProviderFileLoader <init>
SEVERE: Could not find provider class
java.lang.ClassNotFoundException: net.whistlingfish.harmony.protocol.OAReplyProvider
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.jivesoftware.smack.provider.ProviderFileLoader.<init>(ProviderFileLoader.java:80)
    at org.jivesoftware.smack.provider.ProviderFileLoader.<init>(ProviderFileLoader.java:49)
    at net.whistlingfish.harmony.HarmonyClientModule.configure(HarmonyClientModule.java:16)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:259)
    at com.google.inject.spi.Elements.getElements(Elements.java:109)
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
    at com.google.inject.Guice.createInjector(Guice.java:96)
    at com.google.inject.Guice.createInjector(Guice.java:73)
    at com.google.inject.Guice.createInjector(Guice.java:62)
    at com.bwssystems.restfulharmony.HarmonyRestServer.main(HarmonyRestServer.java:45)

maaliskuuta 30, 2016 2:03:23 IP. org.jivesoftware.smack.SmackConfiguration loadSmackClass
WARNING: A startup class 'org.jivesoftware.smack.initializer.VmArgInitializer' could not be loaded.
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.jivesoftware.smack.ConnectionConfiguration.<init>(ConnectionConfiguration.java:66)
    at net.whistlingfish.harmony.HarmonyClient.createConnectionConfig(HarmonyClient.java:311)
    at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:113)
    at com.bwssystems.restfulharmony.HarmonyRestServer.execute(HarmonyRestServer.java:66)
    at com.bwssystems.restfulharmony.HarmonyRestServer.main(HarmonyRestServer.java:49)
Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: org.jivesoftware.smack.initializer.VmArgInitializer
    at org.jivesoftware.smack.SmackConfiguration.<clinit>(SmackConfiguration.java:158)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: org.jivesoftware.smack.initializer.VmArgInitializer
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.jivesoftware.smack.SmackConfiguration.loadSmackClass(SmackConfiguration.java:415)
    at org.jivesoftware.smack.SmackConfiguration.parseClassesToLoad(SmackConfiguration.java:392)
    at org.jivesoftware.smack.SmackConfiguration.processConfigFile(SmackConfiguration.java:359)
    at org.jivesoftware.smack.SmackConfiguration.processConfigFile(SmackConfiguration.java:347)
    at org.jivesoftware.smack.SmackConfiguration.<clinit>(SmackConfiguration.java:155)
    ... 5 more

**Comment by bwssytems** [comment]
It's broke.... lost the package in the build...working on it...
