### ISSUE TITLE
Having issues staying connected to hub on 0.1.6 on OS X 

### ISSUE THREAD

**Issue by ergusto** [bwssytems/restful-harmony#4]
Awesome work with this project. Should hopefully allow for some great home automation if I can get this working. 

Both the harmony hub and the Apple machine are connected via the same ethernet hub. It seems to run fine for a minute or two and then crashes with the following trace. Any advice would be appreciated.

23:02:00.826 [main] INFO  c.b.restfulharmony.HarmonyRestServer - Harmony v0.1.5 rest server running....
23:02:01.091 [main] DEBUG n.w.harmony.HarmonyClient - listener[com.bwssystems.restfulharmony.HarmonyRestServer$1@25bbf683] added
23:02:01.921 [main] DEBUG n.w.harmony.protocol.AuthService - auth token request returned: {"GetUserAuthTokenResult":{"AccountId":0,"UserAuthToken":"XXRNVraOz7Hhf5mPlpTNZwepmbV1rSeGpJqjcYAWr5XT90GFMJ0XwZ/jwV2pWZaP"}}
Exception in thread "main" java.lang.RuntimeException: Failed communicating with Harmony Hub
    at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:182)
    at com.bwssystems.restfulharmony.HarmonyRestServer.execute(HarmonyRestServer.java:66)
    at com.bwssystems.restfulharmony.HarmonyRestServer.main(HarmonyRestServer.java:49)
Caused by: org.jivesoftware.smack.SmackException$ConnectionException
    at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:433)
    at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:808)
    at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:396)
    at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:118)
    ... 2 more

**Comment by ergusto** [comment]
Also not getting any response from the local server on the default port.

**Comment by bwssytems** [comment]
Something is taking out your connection and usually it is due to the network, do you have drops in your wifi from time to time?

**Comment by ergusto** [comment]
The wifi can occasionally be patchy. The hub is placed literally right next to the router though (an Airpot Express). It also doesn't seem to connect at all. If it were a problem with the network dropping I would have expected it to at least connect for a bit? Really wishing that the hub had ethernet right about now.

**Comment by bwssytems** [comment]
So your issue is it doesn't connect at all? Is your Hub getting reassigned IP addresses from the Router? It's best to reserve an IP for the Hub as if it changes the HA Bridge will have a different IP you entered for the HUB.

**Comment by bwssytems** [comment]
Is this still an issue?

**Comment by bwssytems** [comment]
No update, closing
